spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    hikari:
      username: ohgiraffers
      password: ohgiraffers

  jpa:
    show-sql: true    # jpa ? ?? ????? SQL ?? ??? ??? ? ??? ?? ??
    database: mysql   # ??? ???? database
    hibernate:
      ddl-auto: create
      # create : ?????? ?? ? ?????? ?? ???? ???? ??? ??
      #           ??? ???? ???? ?????.
      # create-drop : ???? ?????, ??????? ???? ?? ??? ???.
      #               -> ??? ???? ?? ????.
      # update : ?? ?????? ???? ??? ???? ??? ????? ???.
      #           ??? ???? ??? ???? ?? ?????, ???? ?? ?????.
      # none : ??????? ???? ???? ???. ? ??? ??????? ??? ? ??.
    properties:
      hibernate:
        format_sql: true    # sql ?? ???? ? ?? ??? ? ?? format ?? ??